# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/f9315fbb-7eb9-458b-abc7-db35689e7cda";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f32ef7a8-e175-4e37-a1fa-7b0f98363fff".device = "/dev/disk/by-uuid/f32ef7a8-e175-4e37-a1fa-7b0f98363fff";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/472E-0141";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/4b1bd0fc-47db-472d-afe9-4ec78dd4d8e4";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-42c74e03-2bf6-4435-b1ce-12ed0aa13417".device = "/dev/disk/by-uuid/42c74e03-2bf6-4435-b1ce-12ed0aa13417";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f3aa58ed-f7ad-4343-822c-e58963d8d9c8"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
