# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usb_storage" "usbhid" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3b119b00-45a0-42d5-9eb6-993c6b6bd4b6";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3b119b00-45a0-42d5-9eb6-993c6b6bd4b6".device = "/dev/disk/by-uuid/3b119b00-45a0-42d5-9eb6-993c6b6bd4b6";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B0F0-490C";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/luks-1ecab054-12be-421f-86f5-2912ba7346cc";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1ecab054-12be-421f-86f5-2912ba7346cc".device = "/dev/disk/by-uuid/1ecab054-12be-421f-86f5-2912ba7346cc";

  swapDevices =
    [ { device = "/dev/disk/by-uuid/9b74cafe-edbf-4516-bf4d-159b4bb5dd08"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
